package org.yaukie.api.base.core;

import org.apache.ibatis.annotations.Param;
import tk.mybatis.mapper.entity.Condition;

import java.util.List;

/**
 * @Author: yuenbin
 * @Date :2020/3/20
 * @Time :10:00
 * @Motto: It is better to be clear than to be clever !
 * @Destrib:
 **/
public interface Service<T,E> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    long countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_item
     *
     * @mbg.generated Fri Mar 20 15:28:09 CST 2020
     */
    int updateByPrimaryKey(T record);

}
